import Head from 'next/head'

export default function Pdf() {
  return (
    <>
      <Head>
        <title>PDF | CSV TO PDF</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section>
        <h1>PDF</h1>
      </section>
    </>
  )
}
